# Streamlit Secrets Configuration
# Configure no painel do Streamlit Cloud: https://share.streamlit.io

# ⚠️ OBRIGATÓRIO: Chave da OpenAI (substitua pela sua chave real)
OPENAI_API_KEY = "sk-sua-chave-openai-aqui"

# 🎯 LLM Configuration
LLM_MODEL_NAME = "gpt-4o"

# 🗄️ Database Configuration (OPCIONAL - apenas se quiser conectar SQL Server na nuvem)
# Deixe comentado para usar modo cloud com autenticação local
# DB_SERVER = "seu-servidor-sql-na-nuvem"
# DB_NAME = "Projeto_Caculinha"
# DB_USER = "AgenteVirtual"
# DB_PASSWORD = "sua-senha"
# DB_DRIVER = "ODBC Driver 17 for SQL Server"
# DB_TRUST_SERVER_CERTIFICATE = "yes"

# 👤 Usuários para modo cloud (automático quando SQL Server não disponível):
# admin / admin
# user / user123
# cacula / cacula123