# Streamlit Secrets Configuration
# Configure estas variáveis no painel do Streamlit Cloud

# API Keys
OPENAI_API_KEY = "your-openai-api-key-here"

# Database Configuration
DB_SERVER = "your-server-here"
DB_NAME = "your-database-here"
DB_USER = "your-username-here"
DB_PASSWORD = "your-password-here"
DB_DRIVER = "ODBC Driver 17 for SQL Server"
DB_TRUST_SERVER_CERTIFICATE = "yes"

# LLM Configuration
LLM_MODEL_NAME = "gpt-4o"